---
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create EC2
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        region: us-east-1
        state: started
        wait: true

        key_name: "{{ lookup('aws_ssm', '/JJTech/' + team + '/keyname', region='us-east-1') }}"

        security_groups:
          - "{{ lookup('aws_ssm', '/JJTech/' + team + '/' + security_group, region='us-east-1') }}"

        image_id: "{{ lookup('aws_ssm', '/JJTech/' + team + '/' + ami_type, region='us-east-1') }}"

        instance_type: "{{ instance_type }}"

        vpc_subnet_id: "{{ lookup('aws_ssm', '/JJTech/' + team + '/' + vpc_subnet_id, region='us-east-1') }}"

        iam_instance_profile: "{{ lookup('aws_ssm', '/JJTech/' + team + '/' + instance_role, region='us-east-1') }}"

        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_type: gp2
              volume_size: "{{ root_volume_size | int }}"
              delete_on_termination: true
              encrypted: true

        tags:
          Name: "{{ instance_name }}"
          created_by: "{{ created_by }}"
          Owner: "{{ Owner }}"
          App_Name: "{{ App_Name }}"
          Cost_Center: "{{ Cost_Center }}"
          Business_Unit: "{{ Business_Unit }}"

        user_data: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable --now httpd
          echo "<html><body><h1>Hello JJTech Team</h1></body></html>" > /var/www/html/index.html

      register: ec2_instance

    - name: Show EC2 instance ID
      ansible.builtin.debug:
        var: ec2_instance.instance_ids