---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create an S3 bucket
    amazon.aws.s3_bucket:
      name: "{{ S3_Bucket_Name }}"
      region: eu-west-1
      state: present
